language: node_js
node_js:
- lts/*
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
# From travis-ci.com: "The default user for accessing the local PostgreSQL server is postgres with a blank password."
# The database name (created below) is: "travis_ci_test"
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_836ffb92ea95_key -iv $encrypted_836ffb92ea95_iv
  -in secrets.tar.enc -out secrets.tar -d || echo "no secrets"'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && tar xvf secrets.tar || echo "no secrets.tar"'
- psql -c 'create database travis_ci_test;' -U postgres
before_script: 
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud components install cloud-datastore-emulator
- gcloud beta emulators datastore start --no-store-on-disk &
- $(gcloud beta emulators datastore env-init)
before_deploy: "npm run build-css"
deploy:
  provider: gae
  keyfile: google-keyfile.json
  project: thematic-cider-139815
  config: app-development.yaml
  skip_cleanup: true
  on:
    branch: master

